
baseURL = 'https://mmellet.github.io/modele3'
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Titre"
theme = 'book'

removePathAccents=true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark]
    typographer = true
    [markup.goldmark.renderer]
     footnoteReturnLinkContents = "&uarr;"
      unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookMenuBundle = "/menu"
  BookTheme = "light"
  BookToC = true
  BookSection = 'docs'
  BookSearch = true

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = ""
  weight = 10

#[[menu.after]]
#  name = "Hugo Themes"
#  url = "https://themes.gohugo.io/hugo-book/"
#  weight = 20

[permalinks]
docs = "/docs/:title"
posts = "/posts/:title"
shortcode = "/docs/shortcodes/:title"
pages = "pages/:filename"

[taxonomies]
tag = "tags"

[author]

[outputs]
  page = ["HTML", "print"]

[outputFormats]
  [outputFormats.print]
    mediaType = "text/html" # normal
    rel = "print" # rapport
    baseName = "print" # /print dans l'URL
