# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://mmellet.github.io/modele3'
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Titre"
theme = 'hugo-book'

removePathAccents=true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark]
    typographer = true
    [markup.goldmark.renderer]
     footnoteReturnLinkContents = "&uarr;"
      unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookMenuBundle = "/menu"
  BookTheme = "light"

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/hugo-book/"
  weight = 20

[permalinks]
  docs = "/docs/:title"
  posts = "/posts/:title"

[author]
